### PR TITLE
fix: unit link generation

### LINKED ISSUE #1869: Clicking a unit in the advanced search causes error
When you do a cross-model search that contains a unit and then click the unit name it displays this error:

Image

This might be because it hasn't loaded the model data at that point (might need to refresh the search page before clicking on the unit to clear the model data so that this can be reproduced).

### PR DESCRIPTION
**Pull request by andogq**
## Done

- correctly generate unit links in advanced search
- create not found page for units instead of crashing

## QA

- Pull code
- Run `dotrun clean && dotrun serve`
- Open http://0.0.0.0:8036/search?q=.
- Expand root -> 0 -> units, click on a unit (eg `source/4`)
- Should correctly navigate to source page
- Navigate to junk unit page (add something to end of current URL) for not found page

## Details

- WD-19966
- close #1869 

## Screenshots

https://github.com/user-attachments/assets/14059413-baca-44a3-b337-ac320904d38b

### CODE REVIEW

File: src/pages/EntityDetails/Unit/Unit.tsx [hunk 1]
```diff
@@ -38,23 +41,28 @@ export default function Unit() {
   const machines = useSelector(getModelMachines(modelUUID));
   const isK8s = useAppSelector((state) => isKubernetesModel(state, modelUUID));
 
+  const unit = useMemo(
+    () => (unitIdentifier && units?.[unitIdentifier]) || null,
+    [units, unitIdentifier],
+  );
```
Comment (huwshimi) [inline src/pages/EntityDetails/Unit/Unit.tsx:47]: There's probably no value in a `useMemo` here (it might even be slower) as retrieving the unit will be very fast.

**Review by huwshimi — COMMENTED** [review]
Thanks for this fix, just a couple of small comments.

**Review by huwshimi — APPROVED** [review]
Thanks this looks good now!
