### PR TITLE
fix: show error on initial model error

### LINKED ISSUE #1865: Initial model list errors are not shown
When loading the dashboard if there is an error fetching the models then the spinner is shown indefinitely and no error is displayed.

This error should be handled separately from when there is an error fetching the models when polling for updates.

### PR DESCRIPTION
**Pull request by andogq**
## Done

- previously `modelsLoaded` took precedence over checking `modelError`
- includes test to ensure spinner is hidden and no other content is displayed on the page

## QA

- Pull code
- Run `dotrun clean && dotrun serve`
- Open http://0.0.0.0:8036/
- Apply patch to `model-poller` (see below)
- Open dashboard

<details>
<summary>Patch with error</summary>

```patch
diff --git a/src/store/middleware/model-poller.ts b/src/store/middleware/model-poller.ts
index 39d9b6e6..7012da47 100644
--- a/src/store/middleware/model-poller.ts
+++ b/src/store/middleware/model-poller.ts
@@ -217,6 +217,7 @@ export const modelPollerMiddleware: Middleware<
               const models = await conn.facades.modelManager?.listModels({
                 tag: identity,
               });
+              throw new Error("model loading failure");
               if (models) {
                 reduxStore.dispatch(
                   jujuActions.updateModelList({ models, wsControllerURL }),
```

</details>

## Details

- Close #1865
- WD-19967

## Screenshots

image

### CODE REVIEW

File: src/pages/ModelsIndex/ModelsIndex.tsx [hunk 1]
```diff
@@ -93,33 +93,35 @@ export default function Models() {
...
-      </div>
-    );
-  } else {
-    content = (
-      <div className="models">
-        <ChipGroup chips={{ blocked, alert, running }} />
-        <ModelTableList groupedBy={queryParams.groupedby} filters={filters} />
-      </div>
-    );
+  let content: ReactNode = <></>;
```
Comment (huwshimi) [inline src/pages/ModelsIndex/ModelsIndex.tsx:96]: `null` might be a better default here.

File: src/pages/ModelsIndex/ModelsIndex.test.tsx [hunk 2]
```diff
@@ -187,6 +187,17 @@ describe("Models Index page", () => {
...
   });
 
+  it("clears spinner if initial error occurs", async () => {
+    state.juju.modelsLoaded = false;
+    state.juju.modelsError = "An error occured";
+    renderComponent(<ModelsIndex />, { state });
+    expect(
+      screen.queryByTestId(LoadingSpinnerTestId.LOADING),
+    ).not.toBeInTheDocument();
+    expect(screen.getByText(/An error occured/)).toBeInTheDocument();
```
Comment (huwshimi) [inline src/pages/ModelsIndex/ModelsIndex.test.tsx:197]: As suggested this would be a good candidate for our custom selectors to check that this error appears in a notification, once those have been added to this project..

**Review by huwshimi — APPROVED** [review]
Just one tiny suggestion.

File: src/pages/ModelsIndex/ModelsIndex.test.tsx (hunk 2 above)
Comment (andogq) [reply src/pages/ModelsIndex/ModelsIndex.test.tsx:197]: I will address this in #1879 once this PR merges!
