### PR TITLE
fix: prevent action log modal from breaking out of stacking context

### LINKED ISSUE #1784: Action log modal animates behind sidebar
When opening the action log modal it appears behind the main navigation sidebar while the animation is in progress.

Screen Recording 2024-06-21 at 11 32 24 AM

### PR DESCRIPTION
**Pull request by andogq**
## Done

Feels a little bit wacky, but the issue boils down to elements with an opacity != 0 will create a new stacking context, meaning the z-index set within for the backdrop doesn't interact with the rest of the page (eg navigation bars)

- render modal inside `Portal`

- add to framer element:

  - `position` to create a new stacking context which the modal can't break out of

  - `z-index` to imitate Vanilla's modal backdrop

## QA

- Pull code
- Run `dotrun clean && dotrun serve`
- Open http://0.0.0.0:8036/
- Navigate Models -> a model -> Action Logs -> click a result

## Details

- close #1784 
- WD-20084

## Screenshots

https://github.com/user-attachments/assets/811ba812-0da3-40ae-8884-775e6dc0baee

### CODE REVIEW

File: src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx [hunk 1]
```diff
@@ -420,12 +423,17 @@ export default function ActionLogs() {
           sortable
         />
       )}
-      <FadeIn isActive={Boolean(modalDetails)}>
-        <ActionPayloadModal
-          payload={modalDetails}
-          onClose={() => setModalDetails(null)}
-        />
-      </FadeIn>
+      <Portal>
```
Comment (huwshimi) [inline src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx:426]: I'm surprised this wasn't in a modal already.

File: src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss [hunk 2]
```diff
@@ -28,6 +28,13 @@
     }
   }
 
+  .entity-details__payload-modal {
+    position: relative;
```
Comment (huwshimi) [inline src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss:32]: It might be good to leave a comment here about the stacking context so we know why this is here in the future.

File: src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss [hunk 3]
```diff
@@ -28,6 +28,13 @@
...
+
+    /* Pulled from Vanilla's Modal backdrop */
```
Comment (huwshimi) [inline src/pages/EntityDetails/Model/Logs/ActionLogs/_action-logs.scss:34]: It would be helpful to add a permalink to where this is set in Vanilla, in case this breaks and we need to check if the Vanilla value has changed.

**Review by huwshimi — APPROVED** [review]
Great work figuring this one out.

File: src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx (hunk 1 above)
Comment (andogq) [reply src/pages/EntityDetails/Model/Logs/ActionLogs/ActionLogs.tsx:426]: I thought it was odd...

**Comment by andogq** [comment]
Ready to merge, pending juju-dashboard release.
